# Python fundamentals
## Variable declaration

In [1]:
a = 1
b = 2
a + b

3

## Python list, tuple, dictionary, string and operations
 ** List and tuple declaration **

In [2]:
type((1,2,3))

tuple

In [3]:
type([1,2,3])

list

In [4]:
a = {}
a['a'] = 3
a['b'] = 4
type(a)

dict

In [5]:
a = 'this is a string'
type(a)

str

** Operations on python collections and string**


In [6]:
1 in [1,2,3]


True

In [7]:
1 in (1,2,3)

True

In [8]:
[1] * 3

[1, 1, 1]

In [9]:
a = [i for i in range(1,10)]
a[1:3]

[2, 3]

In [10]:
a = 'this is a string'
a[:4]

'this'

In [11]:
a.split(' ')[0]

'this'

In [12]:
for i in [1,2,3]:
    print(i)

1
2
3


In [13]:
a = {}
a['a'] = 1
a['b'] = 2
for k,v in a.items():
    print(k,v)

b 2
a 1


** More operations on Strings **

In [14]:
print()'a' + str(1))

SyntaxError: invalid syntax (<ipython-input-14-342111bd873f>, line 1)

In [15]:
a = 1
b = 2
c = 3
print('printed values {},{},{}'.format(1,2,3))

printed values 1,2,3


## Reading and Writing CSV files

In [16]:
import csv
%precision 2
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
mpg

[{'': '1',
  'class': 'compact',
  'cty': '18',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(l5)',
  'year': '1999'},
 {'': '2',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m5)',
  'year': '1999'},
 {'': '3',
  'class': 'compact',
  'cty': '20',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '31',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m6)',
  'year': '2008'},
 {'': '4',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '30',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(av)',
  'year': '2008'},
 {'': '5',
  'class': 'compact',
  'cty': '16',
  'cyl': '6',
  'displ': '2.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '26',
  'manufacturer': 'audi',
  'model': 'a4',
  'tran

In [17]:
len(mpg)

234

In [18]:
mpg[0].keys()

dict_keys(['', 'fl', 'class', 'manufacturer', 'drv', 'trans', 'year', 'hwy', 'model', 'cty', 'cyl', 'displ'])

In [19]:
sum(float(d['displ']) for d in mpg)/len(mpg)

3.47

In [20]:
cylinders = set(d['cyl']for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [21]:
CtyMpgByCyl = []
for c in cylinders:
    summpg = 0
    sumcount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            sumcount +=1
    CtyMpgByCyl.append((c, summpg / sumcount))
CtyMpgByCyl.sort(key= lambda x: x[1])
CtyMpgByCyl

[('8', 12.57), ('6', 16.22), ('5', 20.50), ('4', 21.01)]

In [22]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

## Dates and Times

In [23]:
import datetime as dt
import time as tm
tm.time()

1516332983.98

In [24]:
dtnow = dt.datetime.fromtimestamp(tm.time())
print(dtnow)

2018-01-19 10:36:24.169688


In [25]:
delta = dt.timedelta(days=10)
dtnow - delta

datetime.datetime(2018, 1, 9, 10, 36, 24, 169688)

## Advanced Python Objects, map()
** Objects **

In [26]:
class Persion:
    department = 'School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

** map()**

In [27]:
a = [1, 2, 34, 4]
b = [7,8,3,19]
temp = map(min, a, b)
print(list(temp))

[1, 2, 3, 4]


## Lambda and List Comprehensions

In [28]:
test_function = lambda x: x + 2
test_function(3)

5

In [29]:
my_list = [i for i in range(0,100) if i % 2 == 0]
my_list
len([i * j for i in range(10) for j in range(10)])

100

## Numpy

In [30]:
import numpy as np

** Declaration **

In [31]:
a = [1,2,3]
a = np.array(a)

In [32]:
a * 2

array([2, 4, 6])

In [33]:
a = np.ones((2,3))

** Operations **

In [34]:
np.vstack([a, a * 2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [35]:
np.hstack([a, a * 2])

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [36]:
b = np.linspace(0, 5, 9)
b

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [37]:
reshaped = b.reshape([3,3])
reshaped

array([[0.   , 0.625, 1.25 ],
       [1.875, 2.5  , 3.125],
       [3.75 , 4.375, 5.   ]])

reshaped.diagonal()

In [38]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [40]:
a ** 2

array([1, 4, 9])

In [41]:
a.dot(b)

32

In [42]:
np.dot(a,b)

32

In [43]:
c = np.array([b, b ** 2])
c

array([[ 4,  5,  6],
       [16, 25, 36]])

In [44]:
c.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

** Indexing / Slicing **

In [45]:
s = np.arange(13) ** 2

In [46]:
print(s[0], s[-1], s[1:3], s[:3])

0 144 [1 4] [0 1 4]


In [47]:
len(s)

13

In [48]:
t = np.arange(36)
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [49]:
t.resize((6,6))

In [50]:
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [51]:
t[2,3]

15

In [52]:
t[2,:]

array([12, 13, 14, 15, 16, 17])

** Iterating over Arrays **

In [53]:
o = np.random.randint(0,10,(3,4))

In [54]:
for row in o:
    print(row)

[8 3 1 7]
[6 0 4 0]
[4 7 1 5]


In [55]:
o2 = o ** 2
o2

array([[64,  9,  1, 49],
       [36,  0, 16,  0],
       [16, 49,  1, 25]])

In [56]:
for row1, row2 in zip(o, o2):
    print('{} + {} = {}'.format(row1, row2, row1 + row2))

[8 3 1 7] + [64  9  1 49] = [72 12  2 56]
[6 0 4 0] + [36  0 16  0] = [42  0 20  0]
[4 7 1 5] + [16 49  1 25] = [20 56  2 30]
